Config = {}

Config.Animations = {
	
	{
		name  = 'festives',
		label = 'Animacje',
		items = {
	    {label = "Papieros", type = "scenario", data = {anim = "WORLD_HUMAN_SMOKING"}},
	    {label = "Policjant", type = "scenario", data = {anim = "world_human_cop_idles"}},
		{label = "Ochroniarz", type = "scenario", data = {anim = "world_human_guard_stand"}},
	    {label = "Muzyk", type = "scenario", data = {anim = "WORLD_HUMAN_MUSICIAN"}},
	    {label = "Dj", type = "anim", data = {lib = "anim@mp_player_intcelebrationmale@dj", anim = "dj"}},
	    {label = "Picie Piwa", type = "scenario", data = {anim = "WORLD_HUMAN_PARTYING"}},
	    {label = "Rock'n'roll", type = "anim", data = {lib = "mp_player_int_upperrock", anim = "mp_player_int_rock"}},
	    {label = "Fumer un joint", type = "scenario", data = {anim = "WORLD_HUMAN_SMOKING_POT"}},
	    {label = "Graba", type = "anim", data = {lib = "mp_ped_interaction", anim = "handshake_guy_a"}},
	    {label = "Salut", type = "anim", data = {lib = "mp_player_int_uppersalute", anim = "mp_player_int_salute"}},
	    {label = "Zakładnik", type = "anim", data = {lib = "random@arrests@busted", anim = "idle_c"}},
	    {label = "Wędkarz", type = "scenario", data = {anim = "world_human_stand_fishing"}},
	    {label = "Pochylenie się", type = "anim", data = {lib = "amb@code_human_police_investigate@idle_b", anim = "idle_f"}},
	    {label = "Lornetka", type = "scenario", data = {anim = "WORLD_HUMAN_BINOCULARS"}},
	    {label = "Naprawa", type = "anim", data = {lib = "mini@repair", anim = "fixing_a_ped"}},
	    {label = "Medyk", type = "scenario", data = {anim = "CODE_HUMAN_MEDIC_KNEEL"}},
	    {label = "Fotograf", type = "scenario", data = {anim = "WORLD_HUMAN_PAPARAZZI"}},
	    {label = "Notatki", type = "scenario", data = {anim = "WORLD_HUMAN_CLIPBOARD"}},
	    {label = "PAN DA", type = "scenario", data = {anim = "WORLD_HUMAN_BUM_FREEWAY"}},
	    {label = "Statua", type = "scenario", data = {anim = "WORLD_HUMAN_HUMAN_STATUE"}},
	    {label = "Oklaski", type = "scenario", data = {anim = "WORLD_HUMAN_CHEERING"}},
	    {label = "Super", type = "anim", data = {lib = "mp_action", anim = "thanks_male_06"}},
	    {label = "CO JEST?", type = "anim", data = {lib = "gestures@m@standing@casual", anim = "gesture_bring_it_on"}},
	    {label = "Facepalm", type = "anim", data = {lib = "anim@mp_player_intcelebrationmale@face_palm", anim = "face_palm"}},
	    {label = "Uspokój się", type = "anim", data = {lib = "gestures@m@standing@casual", anim = "gesture_easy_now"}},
	    {label = "co to?", type = "anim", data = {lib = "oddjobs@assassinate@multi@", anim = "react_big_variations_a"}},
	    {label = "Przestraszony", type = "anim", data = {lib = "amb@code_human_cower_stand@male@react_cowering", anim = "base_right"}},
	    {label = "Przytul", type = "anim", data = {lib = "mp_ped_interaction", anim = "kisses_guy_a"}},
	    {label = "Fuck You", type = "anim", data = {lib = "mp_player_int_upperfinger", anim = "mp_player_int_finger_01_enter"}},
	    {label = "Muskuły", type = "anim", data = {lib = "amb@world_human_muscle_flex@arms_at_side@base", anim = "base"}},
	    {label = "Pompki", type = "anim", data = {lib = "amb@world_human_push_ups@male@base", anim = "base"}},
	    {label = "Brzuszki", type = "anim", data = {lib = "amb@world_human_sit_ups@male@base", anim = "base"}},
	    {label = "Yoga", type = "anim", data = {lib = "amb@world_human_yoga@male@base", anim = "base_a"}},
	    {label = "Menel", type = "scenario", data = {anim = "WORLD_HUMAN_PICNIC"}},
	    {label = "Oprzyj się", type = "scenario", data = {anim = "world_human_leaning"}},
	    {label = "Leżenie", type = "scenario", data = {anim = "WORLD_HUMAN_SUNBATHE_BACK"}},
	    {label = "Szorowanie", type = "scenario", data = {anim = "world_human_maid_clean"}},
	    {label = "Telefon", type = "scenario", data = {anim = "world_human_tourist_mobile"}},
		}
	},

	{
		name  = 'attitudem',
		label = 'Styl Chodzenia',
		items = {
		{label = "Normalny M1", type = "attitude", data = {lib = "move_m@shocked@a", anim = "move_m@shocked@a"}},
	    {label = "Normalny M2", type = "attitude", data = {lib = "move_m@confident", anim = "move_m@confident"}},
	    {label = "Normalny K", type = "attitude", data = {lib = "move_f@heels@c", anim = "move_f@heels@c"}},
	    {label = "Zrezygnowany", type = "attitude", data = {lib = "move_m@depressed@a", anim = "move_m@depressed@a"}},
	    {label = "Zrezygnowany 2", type = "attitude", data = {lib = "move_m@gangster@var_f", anim = "move_m@gangster@var_f"}},
	    {label = "Zamyślona", type = "attitude", data = {lib = "move_f@depressed@a", anim = "move_f@depressed@a"}},
	    {label = "Sztywniak", type = "attitude", data = {lib = "move_m@business@a", anim = "move_m@business@a"}},
		{label = "Sztywniak 2", type = "attitude", data = {lib = "move_m@gangster@var_e", anim = "move_m@gangster@var_e"}},
	    {label = "Kozak", type = "attitude", data = {lib = "move_m@brave@a", anim = "move_m@brave@a"}},
	    {label = "Zwykły", type = "attitude", data = {lib = "move_m@casual@a", anim = "move_m@casual@a"}},
	    {label = "Odparzone Pachy", type = "attitude", data = {lib = "move_m@fat@a", anim = "move_m@fat@a"}},
	    {label = "Hipster", type = "attitude", data = {lib = "move_m@hipster@a", anim = "move_m@hipster@a"}},
	    {label = "Po przejściach", type = "attitude", data = {lib = "move_m@injured", anim = "move_m@injured"}},
	    {label = "Pośpiech", type = "attitude", data = {lib = "move_m@hurry@a", anim = "move_m@hurry@a"}},
		{label = "Pośpiech 2", type = "attitude", data = {lib = "move_m@hurry_butch@a", anim = "move_m@hurry_butch@a"}},
	    {label = "Pośpiech 3", type = "attitude", data = {lib = "move_m@gangster@var_i", anim = "move_m@gangster@var_i"}},
	    {label = "Zamulony", type = "attitude", data = {lib = "move_m@hobo@a", anim = "move_m@hobo@a"}},
	    {label = "Smutny", type = "attitude", data = {lib = "move_m@sad@a", anim = "move_m@sad@a"}},
	    {label = "Twardziel", type = "attitude", data = {lib = "move_m@muscle@a", anim = "move_m@muscle@a"}},
	    {label = "Gangster", type = "attitude", data = {lib = "move_m@shadyped@a", anim = "move_m@shadyped@a"}},
		{label = "Cwaniak", type = "attitude", data = {lib = "MOVE_M@TOUGH_GUY@", anim = "MOVE_M@TOUGH_GUY@"}},
	    {label = "Wygięty", type = "attitude", data = {lib = "move_m@buzzed", anim = "move_m@buzzed"}},
	    {label = "Swag", type = "attitude", data = {lib = "move_m@money", anim = "move_m@money"}},
	    {label = "Korzeniowski", type = "attitude", data = {lib = "move_m@quick", anim = "move_m@quick"}},
	    {label = "Kobieta 1", type = "attitude", data = {lib = "move_f@maneater", anim = "move_f@maneater"}},
	    {label = "Kobieta 2", type = "attitude", data = {lib = "move_f@sassy", anim = "move_f@sassy"}},	
	    {label = "Kobieta 3", type = "attitude", data = {lib = "move_f@arrogant@a", anim = "move_f@arrogant@a"}},
	    {label = "Kobieta 4", type = "attitude", data = {lib = "MOVE_F@TOUGH_GUY@", anim = "MOVE_F@TOUGH_GUY@"}},
		
		
		}
	},

}