// DO NOT EDIT THIS FILE
// Copy it to `config.js` and edit it
window.CONFIG = {
  defaultTemplateId: 'default', //This is the default template for 2 args1
  defaultAltTemplateId: 'defaultAlt', //This one for 1 arg
  templates: { //You can add static templates here
    'default': '<div style="padding: 0.5vw; margin: 0.2vw; background-color: rgba(255, 0, 0, 0.8); border-radius: 3px;"><b>Bóg:</b><br> {1}</div>',
    'defaultAlt': '{0}',
    'print': '<pre>{0}</pre>',
    'example:important': '<h1>^2{0}</h1>'
  },
  fadeTimeout: 7000,
  suggestionLimit: 5,
  style: {
    background: 'transparent',
    width: '38%',
    height: '22%',
  }
};

//   templates: { //You can add static templates here
    //'default': '<div class="chat-message"><b>{0}</b>:</div><div class="chat-message-body">{1}</div>',
    //'defaultAlt': '{0}',
    //'print': '<pre>{0}</pre>',
    //'example:important': '<h1>^2{0}</h1>'
  //},
